from setuptools import setup

package_name = 'serial_motor_demo'

setup(
    name=package_name,
    version='0.0.0',
    packages=[package_name],
    data_files=[
        ('share/ament_index/resource_index/packages',
            ['resource/' + package_name]),
        ('share/' + package_name, ['package.xml']),
    ],
    install_requires=['setuptools'],
    zip_safe=True,
    maintainer='newans',
    maintainer_email='josh.newans@gmail.com',
    description='TODO: Package description',
    license='TODO: License declaration',
    tests_require=['pytest'],
    entry_points={
        'console_scripts': [
            'gui = serial_motor_demo.gui:main',
            'driver = serial_motor_demo.driver:main',
            'datatransfer = serial_motor_demo.datatransfer:main',
            'speedtopwm = serial_motor_demo.speedtopwm:main',
            'send = serial_motor_demo.send:main',
            'receive = serial_motor_demo.receive:main',
            'stm_to_odom = serial_motor_demo.stm_to_odom:main',
            'odom_to_base_transform = serial_motor_demo.odom_to_base_transform:main',
            'meccanum_drive_node = serial_motor_demo.meccanum_drive_node:main',
            '3_encoder = serial_motor_demo.3_encoder:main',
            'send2 = serial_motor_demo.send2:main',
            'teleop_pwm = serial_motor_demo.teleop_pwm:main',
            'receive_STM = serial_motor_demo.receive_STM:main',
            'receive_IMU = serial_motor_demo.receive_IMU:main',
            'fake_odom = serial_motor_demo.fake_odom:main',
            'imu_to_odom = serial_motor_demo.imu_to_odom:main',
            'EKF = serial_motor_demo.EKF:main',
            'test_joy = serial_motor_demo.test_joy:main',
            'PID_Controller = serial_motor_demo.PID_Controller:main',
            'PID_Key = serial_motor_demo.PID_Key:main',
            'odometry_comparison = serial_motor_demo.odometry_comparison:main',
            'serial = serial_motor_demo.serial:main',
            'IMU_testing = serial_motor_demo.IMU_testing:main',
            'EKF_final = serial_motor_demo.EKF_final:main',
            'ARM = serial_motor_demo.ARM:main',
            'OpenLoop_key = serial_motor_demo.OpenLoop_key:main',
            'OpenLoop_controller = serial_motor_demo.OpenLoop_controller:main',
            'dynamic_tf_broadcaster = serial_motor_demo.dynamic_tf_broadcaster:main',
            'scan_timestamp_fixer = serial_motor_demo.scan_timestamp_fixer:main',
            'raw_odom_publisher = serial_motor_demo.raw_odom_publisher:main',
            'cmd_vel_to_pwm = serial_motor_demo.cmd_vel_to_pwm:main',
        ],
    },
)
